# We define two jobs:
# - "Check Style": it only runs a simple style checker script
# - "Compile & Test": this actually needs Rust and compiles everything
matrix:
  fast_finish: true
  allow_failures:
    - name: "Compile & Test WASM"
  include:
    - name: "Check style"
      language: generic
      script: ./ci/check-basic-style.sh
    - name: "Compile & Test Desktop"
      language: rust
      rust: nightly
      env:
        - RUSTFLAGS="--deny warnings"
      before_script:
        - sudo apt-get install xorg-dev
      script:
        - cargo build --verbose -p mahboi -p mahboi-desktop
        - cargo test --verbose -p mahboi -p mahboi-desktop
      # speeds up travis build
      cache: cargo
