language: rust
rust: nightly


before_script:
  - sudo apt-get install xorg-dev

script:
  - ci/check-basic-style.sh
  - cargo build --verbose
  - cargo test --verbose

env:
  - RUSTFLAGS="--deny warnings"

# speeds up travis build
cache: cargo
