cargo-features = ["edition"]

[package]
name = "mahboi"
version = "0.1.0"
authors = ["Lukas Kalbertodt <lukas.kalbertodt@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4"

[build-dependencies]
failure = "0.1.2"
reqwest = "0.8"
