[package]
name = "mahboi-desktop"
version = "0.1.0"
authors = ["Lukas Kalbertodt <lukas.kalbertodt@gmail.com>"]
edition = "2018"

[dependencies]
failure = "0.1.2"
lazy_static = "1.1"
log = { version = "0.4", features = ["release_max_level_debug"] }
mahboi = { path = "../core" }
minifb = "0.11"
structopt = "0.2"
unicode-width = "0.1.5"
spin_sleep = "0.3"

[target.'cfg(not(windows))'.dependencies]
cursive = "0.12.0"
ncurses = "5"
