cargo-features = ["edition"]

[package]
name = "mahboi-desktop"
version = "0.1.0"
authors = ["Lukas Kalbertodt <lukas.kalbertodt@gmail.com>"]
edition = "2018"

[dependencies]
failure = "0.1.2"
mahboi = { path = "../core" }
minifb = "0.10"
structopt = "0.2"
termion = "1.5"
tui = "0.2.3"
